[package]
name = "blog_backend"
version = "0.1.0"
authors = ["Kamil Koczurek <koczurekk@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.5.5"
sha2 = "0.8.0"
dotenv = "0.9.0"
rocket = "0.4.0-rc.1"
rocket_contrib = "0.4.0-rc.1"
diesel = { version = "1.0.0", features = ["mysql"] }
