[package]
name = "blog_backend"
version = "0.1.0"
authors = ["Kamil Koczurek <koczurekk@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
diesel = { version = "1.0.0", features = ["mysql"] }
dotenv = "0.9.0"
